symlinks:
  upg.sh: /home/brl0/dotfiles/.files/scripts/upgrades.sh
  scripts: /home/brl0/dotfiles/.files/scripts/
  c: /mnt/c/
  local_c: /mnt/c/local/
  .aws: /mnt/c/Users/b_r_l/.aws/
  .azure: /mnt/c/Users/b_r_l/.azure/
  .env: /mnt/c/Users/b_r_l/.env
  .kaggle: /mnt/c/Users/b_r_l/.kaggle/
  b_r_l: /mnt/c/Users/b_r_l/
  downloads: /mnt/c/Users/b_r_l/Downloads/
  g: /mnt/c/Users/b_r_l/Google\ Drive/
  gdrive: /mnt/c/Users/b_r_l/Google\ Drive/
  o: /mnt/c/Users/b_r_l/OneDrive/
  one: /mnt/c/Users/b_r_l/OneDrive/
  onedrive: /mnt/c/Users/b_r_l/OneDrive/
  .gnupg: /mnt/c/Users/b_r_l/OneDrive/.gnupg/
  docs: /mnt/c/Users/b_r_l/OneDrive/Documents/
  Documents: /mnt/c/Users/b_r_l/OneDrive/Documents/
  backup: /mnt/c/Users/b_r_l/OneDrive/Documents/backup/
  brl: /mnt/c/Users/b_r_l/OneDrive/Documents/BRL/
  code: /mnt/c/Users/b_r_l/OneDrive/Documents/code/
  projects: /mnt/c/Users/b_r_l/OneDrive/Documents/projects/
  wsl: /mnt/c/Users/b_r_l/OneDrive/wsl/
  d: /mnt/d/
  local: /mnt/d/local/
  local_d: /mnt/d/local/
  e: /mnt/e/
  local_e: /mnt/e/local/
