[pipx]
command=mamba run pipx install
mode=single
packages:
  pre-commit

[xpip]
# shell=mamba run xonsh -c
command=mamba run xonsh -c xpip install -U
mode=multi
packages:
  xonsh-autoxsh
  xontrib-abbrevs
  xontrib-back2dir
  xontrib-bash-completions-dirs
  xontrib-bashisms
  xontrib-clp
  xontrib-cmd-durations
  xontrib-commands
  xontrib-dalias[dict,yaml]
  xontrib-ergopack[dev,onepath,prompt]
  xontrib-fzf-completions
  xontrib-hist-format
  xontrib-history-encrypt
  xontrib-homebrew
  xontrib-jedi
  xontrib-jump-to-dir
  xontrib-jupyter
  xontrib-langenv
  xontrib-onepath
  xontrib-output-search
  xontrib-pipeliner
  xontrib-prompt-bar
  xontrib-prompt-starship
  xontrib-pyrtn
  xontrib-readable-traceback
  xontrib-sh
  xontrib-whole-word-jumping
  xontrib-xlsd
  xontrib-z
  timg
