[webi]
command=curl -sS https://webi.sh/webi | sh

[env]
command=source ~/.config/envman/PATH.env

[webi_pkgs]
command=webi
# command=~/.local/bin/webi
mode=single
packages:
  aliasman
  # brew
  dotenv
  dotenv-linter
  pathman

[x]
command=eval "$(curl https://get.x-cmd.com)" && . ~/.x-cmd.root/X

[x_pkgs]
command=~/.x-cmd.root/bin/x env use
mode=multi
packages:
  jc

[brew_env]
command=eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

[brew_update]
command=brew update

[brew_pkgs]
command=brew install
mode=multi
packages:
  # shell fun
  asdf
  # bash-completion@2
  direnv
  fzf
  lsd  # nicer ls
  navi
  starship  # prompt configuration
  # tools
  gh
  jq
  ripgrep-all
  # linters
  shellcheck
  shfmt
  sqlfluff
  vale
  # package managers
  micromamba
  nvm  # node version manager
  pkgx
  topgrade
  # ai
  localai

[micromamba]
command=mamba install -y
mode=multi
packages:
  python
  # package managers
  conda
  hatch
  pip
  pipx
  poetry
  uv
  # jupyter
  ipykernel
  nb_conda_kernels
  # shell
  argcomplete
  ipython
  prompt_toolkit
  xonsh
  # linters
  black
  mypy
  pylint
  gitpython

[conda_init]
command=conda init

[pip]
command=conda run pip install -U
mode=multi
packages:
  flake8 flake8-bugbear flake8-docstrings flake8-import-order flake8-quotes
  euporie[all]
  konch
  xonsh[full]
  python-lsp-server[all]
  # powerline-status

[pipx]
command=conda run pipx install -U
mode=single
packages:
  pre-commit

[xpip]
shell=conda run xonsh -c
command=xpip install -U
mode=multi
packages:
  xonsh-autoxsh
  xontrib-abbrevs
  xontrib-back2dir
  xontrib-bash-completions-dirs
  xontrib-bashisms
  xontrib-clp
  xontrib-cmd-durations
  xontrib-commands
  xontrib-dalias[dict,yaml]
  xontrib-ergopack[dev,onepath,prompt]
  xontrib-fzf-completions
  xontrib-hist-format
  xontrib-history-encrypt
  xontrib-homebrew
  xontrib-jedi
  xontrib-jump-to-dir
  xontrib-jupyter
  xontrib-langenv
  xontrib-onepath
  xontrib-output-search
  xontrib-pipeliner
  xontrib-prompt-bar
  xontrib-prompt-starship
  xontrib-pyrtn
  xontrib-readable-traceback
  xontrib-sh
  xontrib-whole-word-jumping
  xontrib-xlsd
  xontrib-z
  timg
