[webi]
pre:
  curl -sS https://webi.sh/webi | sh
  source ~/.config/envman/PATH.env
install=webi
# command=~/.local/bin/webi
mode=single
packages:
  aliasman
  # brew
  dotenv
  dotenv-linter
  pathman

[brew_pkgs]
pre:
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  brew update
install=brew install
mode=multi
packages:
  # shell fun
  asdf
  # bash-completion@2
  direnv
  fzf
  lsd  # nicer ls
  navi
  starship  # prompt configuration
  # tools
  gh
  jq
  ripgrep-all
  # linters
  shellcheck
  shfmt
  sqlfluff
  vale
  # package managers
  micromamba
  nvm  # node version manager
  pkgx
  topgrade
  # ai
  localai

[micromamba]
command=mamba install -y
mode=multi
packages:
  python
  # package managers
  conda
  hatch
  pip
  pipx
  poetry
  uv
  # jupyter
  ipykernel
  nb_conda_kernels
  # shell
  argcomplete
  ipython
  prompt_toolkit
  xonsh
  # linters
  black
  mypy
  pylint
  ruff
  # other
  gitpython

[pip]
command=mamba run pip install -U
mode=multi
packages:
  flake8 flake8-bugbear flake8-import-order flake8-quotes  # flake8-docstrings
  euporie[all]
  konch
  xonsh[full]
  python-lsp-server[all]
  # powerline-status
