[apt]
command=apt-get install -y
mode=multi
packages:
  curl
  wget
  git
  unzip
  build-essential
  htop
  tree
  bash-completion
  bash-doc
  libsixel-bin  # prereq
  imagemagick  # prereq
  socat  # prereq
  dbus
